### ISSUE TITLE
stars count seems out of date

### ISSUE THREAD

**Issue by wwood** [pjotrp/biogems.info#77]
I just noticed that sequenceserver has 30 on biogems.info, but 53 on https://github.com/yannickwurm/sequenceserver

**Comment by pjotrp** [comment]
It is the github API that needs iteration (we only fetch the first batch). Feel free to improve on it. See 

https://github.com/pjotrp/biogems.info/blob/master/lib/biogems/github.rb#L23

**Comment by wwood** [comment]
If you are just looking for the number of stargazers, then it might be
easier to parse out the "stargazers_count" from the repo i.e.

https://api.github.com/repos/bioruby/bioruby

I've tried cloning biogems.info in the past to try to get it going myself
in the past and not had a lot of success, so I'm probably not going to be
able to help with the actual coding, I'm afraid.


On 4 February 2015 at 17:40, Pjotr Prins <notifications@github.com> wrote:

> It is the github API that needs iteration (we only fetch the first batch).
> Feel free to improve on it. See
>
>
> https://github.com/pjotrp/biogems.info/blob/master/lib/biogems/github.rb#L23
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pjotrp/biogems.info/issues/77#issuecomment-72804046>.
>



-- 
--
Ben Woodcroft
http://ecogenomic.org/users/ben-woodcroft <http://www.ecogenomic.org/>

**Comment by pjotrp** [comment]
Good one, I have missed that overview. We can lift out more data from there...

**Comment by pjotrp** [comment]
Works.

**Comment by wwood** [comment]
Cool, thanks.

On 5 February 2015 at 18:31, Pjotr Prins <notifications@github.com> wrote:

> Works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pjotrp/biogems.info/issues/77#issuecomment-73011123>.
>



-- 
--
Ben Woodcroft
http://ecogenomic.org/users/ben-woodcroft <http://www.ecogenomic.org/>
