### ISSUE TITLE
SequenceServer's build status badge should point to 1.0.x branch.

### ISSUE THREAD

**Issue by yeban** [pjotrp/biogems.info#83]
We moved the stable release to 1.0.x branch and are continuing with development on master. It will be a while before the next stable release is out. In the meantime biogems.info should show build status on the stable branch.

I think I will have to add a key to [SequenceServer's override file](https://github.com/pjotrp/biogems.info/blob/master/etc/biogems/sequenceserver.yaml) to do that, but I'm not sure what should the key be. Please could you help us with that @pjotrp, and I will send a PR.

Thanks.

**Comment by pjotrp** [comment]
I don't know how to override. Generally master is the stable branch and others are for development.
