### ISSUE TITLE
quick question- Bio dependancies?

### ISSUE THREAD

**Issue by mjy** [pjotrp/biogems.info#88]
@pjotrp besides the namespacing, does this library require code outside of /lib?  My superficial assessment is that it doesn't. 

It's been a while since I've dived into /bio, so this is an ignorant question,  but could you  briefly highlight reasons for not extracting this library to a stand-alone gem without the overhead of the rest of bio?

**Comment by pjotrp** [comment]
This repo generates the website http://biogems.info/

**Comment by mjy** [comment]
Doh! Sorry, multiple windows open and I meant to open this at https://github.com/nexml/bio-nexml.
